//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 11:30:18 AM CEST 
//


package org.gbif.doi.metadata.datacite;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.google.common.base.Objects;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;


/**
 * <p>Java class for box complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="box">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="westBoundLongitude" type="{http://datacite.org/schema/kernel-4}longitudeType"/>
 *         &lt;element name="eastBoundLongitude" type="{http://datacite.org/schema/kernel-4}longitudeType"/>
 *         &lt;element name="southBoundLatitude" type="{http://datacite.org/schema/kernel-4}latitudeType"/>
 *         &lt;element name="northBoundLatitude" type="{http://datacite.org/schema/kernel-4}latitudeType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "box", propOrder = {

})
public class Box {

    protected float westBoundLongitude;
    protected float eastBoundLongitude;
    protected float southBoundLatitude;
    protected float northBoundLatitude;

    /**
     * Gets the value of the westBoundLongitude property.
     * 
     */
    public float getWestBoundLongitude() {
        return westBoundLongitude;
    }

    /**
     * Sets the value of the westBoundLongitude property.
     * 
     */
    public void setWestBoundLongitude(float value) {
        this.westBoundLongitude = value;
    }

    /**
     * Gets the value of the eastBoundLongitude property.
     * 
     */
    public float getEastBoundLongitude() {
        return eastBoundLongitude;
    }

    /**
     * Sets the value of the eastBoundLongitude property.
     * 
     */
    public void setEastBoundLongitude(float value) {
        this.eastBoundLongitude = value;
    }

    /**
     * Gets the value of the southBoundLatitude property.
     * 
     */
    public float getSouthBoundLatitude() {
        return southBoundLatitude;
    }

    /**
     * Sets the value of the southBoundLatitude property.
     * 
     */
    public void setSouthBoundLatitude(float value) {
        this.southBoundLatitude = value;
    }

    /**
     * Gets the value of the northBoundLatitude property.
     * 
     */
    public float getNorthBoundLatitude() {
        return northBoundLatitude;
    }

    /**
     * Sets the value of the northBoundLatitude property.
     * 
     */
    public void setNorthBoundLatitude(float value) {
        this.northBoundLatitude = value;
    }

    public static Box.Builder<Void> builder() {
        return new Box.Builder<Void>(null, null, false);
    }

    public static Box.Builder<Void> copyOf(final Box _other) {
        return new Box.Builder<Void>(null, _other, true);
    }

    public static Box.Builder<Void> copyOf(final Box _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Box.Builder<Void>(null, _other, true, _propertyTree, _propertyTreeUse);
    }

    public static Box.Builder<Void> copyExcept(final Box _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Box.Builder<Void> copyOnly(final Box _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    @Override
    public String toString() {
        return Objects.toStringHelper(this).add("westBoundLongitude", westBoundLongitude).add("eastBoundLongitude", eastBoundLongitude).add("southBoundLatitude", southBoundLatitude).add("northBoundLatitude", northBoundLatitude).toString();
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(westBoundLongitude, eastBoundLongitude, southBoundLatitude, northBoundLatitude);
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (getClass()!= other.getClass()) {
            return false;
        }
        final Box o = ((Box) other);
        return (((Objects.equal(westBoundLongitude, o.westBoundLongitude)&&Objects.equal(eastBoundLongitude, o.eastBoundLongitude))&&Objects.equal(southBoundLatitude, o.southBoundLatitude))&&Objects.equal(northBoundLatitude, o.northBoundLatitude));
    }

    public static class Builder<TParentBuilder >{

        protected final TParentBuilder _parentBuilder;
        protected final Box _product;
        private float westBoundLongitude;
        private float eastBoundLongitude;
        private float southBoundLatitude;
        private float northBoundLatitude;

        public Builder(final TParentBuilder _parentBuilder, final Box _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_copy) {
                this._product = null;
                this.westBoundLongitude = _other.westBoundLongitude;
                this.eastBoundLongitude = _other.eastBoundLongitude;
                this.southBoundLatitude = _other.southBoundLatitude;
                this.northBoundLatitude = _other.northBoundLatitude;
            } else {
                this._product = _other;
            }
        }

        public Builder(final TParentBuilder _parentBuilder, final Box _other, final boolean _copy, final PropertyTree propertyTree, final PropertyTreeUse treeUse) {
            this._parentBuilder = _parentBuilder;
            if (_copy) {
                this._product = null;
                final PropertyTree westBoundLongitudePropertyTree = ((propertyTree == null)?null:propertyTree.get("westBoundLongitude"));
                if (((treeUse == PropertyTreeUse.INCLUDE)?(westBoundLongitudePropertyTree!= null):((westBoundLongitudePropertyTree == null)||(!westBoundLongitudePropertyTree.isLeaf())))) {
                    this.westBoundLongitude = _other.westBoundLongitude;
                }
                final PropertyTree eastBoundLongitudePropertyTree = ((propertyTree == null)?null:propertyTree.get("eastBoundLongitude"));
                if (((treeUse == PropertyTreeUse.INCLUDE)?(eastBoundLongitudePropertyTree!= null):((eastBoundLongitudePropertyTree == null)||(!eastBoundLongitudePropertyTree.isLeaf())))) {
                    this.eastBoundLongitude = _other.eastBoundLongitude;
                }
                final PropertyTree southBoundLatitudePropertyTree = ((propertyTree == null)?null:propertyTree.get("southBoundLatitude"));
                if (((treeUse == PropertyTreeUse.INCLUDE)?(southBoundLatitudePropertyTree!= null):((southBoundLatitudePropertyTree == null)||(!southBoundLatitudePropertyTree.isLeaf())))) {
                    this.southBoundLatitude = _other.southBoundLatitude;
                }
                final PropertyTree northBoundLatitudePropertyTree = ((propertyTree == null)?null:propertyTree.get("northBoundLatitude"));
                if (((treeUse == PropertyTreeUse.INCLUDE)?(northBoundLatitudePropertyTree!= null):((northBoundLatitudePropertyTree == null)||(!northBoundLatitudePropertyTree.isLeaf())))) {
                    this.northBoundLatitude = _other.northBoundLatitude;
                }
            } else {
                this._product = _other;
            }
        }

        public TParentBuilder end() {
            return this._parentBuilder;
        }

        protected<P extends Box >P init(final P product) {
            product.westBoundLongitude = this.westBoundLongitude;
            product.eastBoundLongitude = this.eastBoundLongitude;
            product.southBoundLatitude = this.southBoundLatitude;
            product.northBoundLatitude = this.northBoundLatitude;
            return product;
        }

        /**
         * Sets the new value of "westBoundLongitude" (any previous value will be replaced)
         * 
         * @param westBoundLongitude
         *     New value of the "westBoundLongitude" property.
         */
        public Box.Builder<TParentBuilder> withWestBoundLongitude(final float westBoundLongitude) {
            this.westBoundLongitude = westBoundLongitude;
            return this;
        }

        /**
         * Sets the new value of "eastBoundLongitude" (any previous value will be replaced)
         * 
         * @param eastBoundLongitude
         *     New value of the "eastBoundLongitude" property.
         */
        public Box.Builder<TParentBuilder> withEastBoundLongitude(final float eastBoundLongitude) {
            this.eastBoundLongitude = eastBoundLongitude;
            return this;
        }

        /**
         * Sets the new value of "southBoundLatitude" (any previous value will be replaced)
         * 
         * @param southBoundLatitude
         *     New value of the "southBoundLatitude" property.
         */
        public Box.Builder<TParentBuilder> withSouthBoundLatitude(final float southBoundLatitude) {
            this.southBoundLatitude = southBoundLatitude;
            return this;
        }

        /**
         * Sets the new value of "northBoundLatitude" (any previous value will be replaced)
         * 
         * @param northBoundLatitude
         *     New value of the "northBoundLatitude" property.
         */
        public Box.Builder<TParentBuilder> withNorthBoundLatitude(final float northBoundLatitude) {
            this.northBoundLatitude = northBoundLatitude;
            return this;
        }

        public Box build() {
            if (this._product == null) {
                return this.init(new Box());
            } else {
                return ((Box) this._product);
            }
        }

    }

    public static class Select
        extends Box.Selector<Box.Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Box.Select _root() {
            return new Box.Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {


        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            return products;
        }

    }

}
