//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 03:13:12 PM CET 
//


package org.gbif.doi.metadata.datacite;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gbif.doi.metadata.datacite package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataCiteMetadataDescriptionsDescriptionBr_QNAME = new QName("http://datacite.org/schema/kernel-3", "br");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gbif.doi.metadata.datacite
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataCiteMetadata }
     * 
     */
    public DataCiteMetadata createDataCiteMetadata() {
        return new DataCiteMetadata();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.GeoLocations }
     * 
     */
    public DataCiteMetadata.GeoLocations createDataCiteMetadataGeoLocations() {
        return new DataCiteMetadata.GeoLocations();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Descriptions }
     * 
     */
    public DataCiteMetadata.Descriptions createDataCiteMetadataDescriptions() {
        return new DataCiteMetadata.Descriptions();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.RightsList }
     * 
     */
    public DataCiteMetadata.RightsList createDataCiteMetadataRightsList() {
        return new DataCiteMetadata.RightsList();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.RelatedIdentifiers }
     * 
     */
    public DataCiteMetadata.RelatedIdentifiers createDataCiteMetadataRelatedIdentifiers() {
        return new DataCiteMetadata.RelatedIdentifiers();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.AlternateIdentifiers }
     * 
     */
    public DataCiteMetadata.AlternateIdentifiers createDataCiteMetadataAlternateIdentifiers() {
        return new DataCiteMetadata.AlternateIdentifiers();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Dates }
     * 
     */
    public DataCiteMetadata.Dates createDataCiteMetadataDates() {
        return new DataCiteMetadata.Dates();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Contributors }
     * 
     */
    public DataCiteMetadata.Contributors createDataCiteMetadataContributors() {
        return new DataCiteMetadata.Contributors();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Contributors.Contributor }
     * 
     */
    public DataCiteMetadata.Contributors.Contributor createDataCiteMetadataContributorsContributor() {
        return new DataCiteMetadata.Contributors.Contributor();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Subjects }
     * 
     */
    public DataCiteMetadata.Subjects createDataCiteMetadataSubjects() {
        return new DataCiteMetadata.Subjects();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Titles }
     * 
     */
    public DataCiteMetadata.Titles createDataCiteMetadataTitles() {
        return new DataCiteMetadata.Titles();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Creators }
     * 
     */
    public DataCiteMetadata.Creators createDataCiteMetadataCreators() {
        return new DataCiteMetadata.Creators();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Creators.Creator }
     * 
     */
    public DataCiteMetadata.Creators.Creator createDataCiteMetadataCreatorsCreator() {
        return new DataCiteMetadata.Creators.Creator();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Identifier }
     * 
     */
    public DataCiteMetadata.Identifier createDataCiteMetadataIdentifier() {
        return new DataCiteMetadata.Identifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.ResourceType }
     * 
     */
    public DataCiteMetadata.ResourceType createDataCiteMetadataResourceType() {
        return new DataCiteMetadata.ResourceType();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Sizes }
     * 
     */
    public DataCiteMetadata.Sizes createDataCiteMetadataSizes() {
        return new DataCiteMetadata.Sizes();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Formats }
     * 
     */
    public DataCiteMetadata.Formats createDataCiteMetadataFormats() {
        return new DataCiteMetadata.Formats();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.GeoLocations.GeoLocation }
     * 
     */
    public DataCiteMetadata.GeoLocations.GeoLocation createDataCiteMetadataGeoLocationsGeoLocation() {
        return new DataCiteMetadata.GeoLocations.GeoLocation();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Descriptions.Description }
     * 
     */
    public DataCiteMetadata.Descriptions.Description createDataCiteMetadataDescriptionsDescription() {
        return new DataCiteMetadata.Descriptions.Description();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.RightsList.Rights }
     * 
     */
    public DataCiteMetadata.RightsList.Rights createDataCiteMetadataRightsListRights() {
        return new DataCiteMetadata.RightsList.Rights();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.RelatedIdentifiers.RelatedIdentifier }
     * 
     */
    public DataCiteMetadata.RelatedIdentifiers.RelatedIdentifier createDataCiteMetadataRelatedIdentifiersRelatedIdentifier() {
        return new DataCiteMetadata.RelatedIdentifiers.RelatedIdentifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.AlternateIdentifiers.AlternateIdentifier }
     * 
     */
    public DataCiteMetadata.AlternateIdentifiers.AlternateIdentifier createDataCiteMetadataAlternateIdentifiersAlternateIdentifier() {
        return new DataCiteMetadata.AlternateIdentifiers.AlternateIdentifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Dates.Date }
     * 
     */
    public DataCiteMetadata.Dates.Date createDataCiteMetadataDatesDate() {
        return new DataCiteMetadata.Dates.Date();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Contributors.Contributor.NameIdentifier }
     * 
     */
    public DataCiteMetadata.Contributors.Contributor.NameIdentifier createDataCiteMetadataContributorsContributorNameIdentifier() {
        return new DataCiteMetadata.Contributors.Contributor.NameIdentifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Subjects.Subject }
     * 
     */
    public DataCiteMetadata.Subjects.Subject createDataCiteMetadataSubjectsSubject() {
        return new DataCiteMetadata.Subjects.Subject();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Titles.Title }
     * 
     */
    public DataCiteMetadata.Titles.Title createDataCiteMetadataTitlesTitle() {
        return new DataCiteMetadata.Titles.Title();
    }

    /**
     * Create an instance of {@link DataCiteMetadata.Creators.Creator.NameIdentifier }
     * 
     */
    public DataCiteMetadata.Creators.Creator.NameIdentifier createDataCiteMetadataCreatorsCreatorNameIdentifier() {
        return new DataCiteMetadata.Creators.Creator.NameIdentifier();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://datacite.org/schema/kernel-3", name = "br", scope = DataCiteMetadata.Descriptions.Description.class)
    public JAXBElement<String> createDataCiteMetadataDescriptionsDescriptionBr(String value) {
        return new JAXBElement<String>(_DataCiteMetadataDescriptionsDescriptionBr_QNAME, String.class, DataCiteMetadata.Descriptions.Description.class, value);
    }

}
