//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 12:12:51 PM CET 
//


package org.gbif.doi.datacite;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gbif.doi.datacite package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataCiteMetadataV3DescriptionDescriptionBr_QNAME = new QName("http://datacite.org/schema/kernel-3", "br");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gbif.doi.datacite
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 }
     * 
     */
    public DataCiteMetadataV3 createDataCiteMetadataV3() {
        return new DataCiteMetadataV3();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .GeoLocations }
     * 
     */
    public DataCiteMetadataV3 .GeoLocations createDataCiteMetadataV3GeoLocations() {
        return new DataCiteMetadataV3 .GeoLocations();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Description }
     * 
     */
    public DataCiteMetadataV3 .Description createDataCiteMetadataV3Description() {
        return new DataCiteMetadataV3 .Description();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .RightsList }
     * 
     */
    public DataCiteMetadataV3 .RightsList createDataCiteMetadataV3RightsList() {
        return new DataCiteMetadataV3 .RightsList();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .RelatedIdentifiers }
     * 
     */
    public DataCiteMetadataV3 .RelatedIdentifiers createDataCiteMetadataV3RelatedIdentifiers() {
        return new DataCiteMetadataV3 .RelatedIdentifiers();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .AlternateIdentifiers }
     * 
     */
    public DataCiteMetadataV3 .AlternateIdentifiers createDataCiteMetadataV3AlternateIdentifiers() {
        return new DataCiteMetadataV3 .AlternateIdentifiers();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Dates }
     * 
     */
    public DataCiteMetadataV3 .Dates createDataCiteMetadataV3Dates() {
        return new DataCiteMetadataV3 .Dates();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Contributors }
     * 
     */
    public DataCiteMetadataV3 .Contributors createDataCiteMetadataV3Contributors() {
        return new DataCiteMetadataV3 .Contributors();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Contributors.Contributor }
     * 
     */
    public DataCiteMetadataV3 .Contributors.Contributor createDataCiteMetadataV3ContributorsContributor() {
        return new DataCiteMetadataV3 .Contributors.Contributor();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Subjects }
     * 
     */
    public DataCiteMetadataV3 .Subjects createDataCiteMetadataV3Subjects() {
        return new DataCiteMetadataV3 .Subjects();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Titles }
     * 
     */
    public DataCiteMetadataV3 .Titles createDataCiteMetadataV3Titles() {
        return new DataCiteMetadataV3 .Titles();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Creators }
     * 
     */
    public DataCiteMetadataV3 .Creators createDataCiteMetadataV3Creators() {
        return new DataCiteMetadataV3 .Creators();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Creators.Creator }
     * 
     */
    public DataCiteMetadataV3 .Creators.Creator createDataCiteMetadataV3CreatorsCreator() {
        return new DataCiteMetadataV3 .Creators.Creator();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .NameIdentifier }
     * 
     */
    public DataCiteMetadataV3 .NameIdentifier createDataCiteMetadataV3NameIdentifier() {
        return new DataCiteMetadataV3 .NameIdentifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .ResourceType }
     * 
     */
    public DataCiteMetadataV3 .ResourceType createDataCiteMetadataV3ResourceType() {
        return new DataCiteMetadataV3 .ResourceType();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Sizes }
     * 
     */
    public DataCiteMetadataV3 .Sizes createDataCiteMetadataV3Sizes() {
        return new DataCiteMetadataV3 .Sizes();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Format }
     * 
     */
    public DataCiteMetadataV3 .Format createDataCiteMetadataV3Format() {
        return new DataCiteMetadataV3 .Format();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .GeoLocations.GeoLocation }
     * 
     */
    public DataCiteMetadataV3 .GeoLocations.GeoLocation createDataCiteMetadataV3GeoLocationsGeoLocation() {
        return new DataCiteMetadataV3 .GeoLocations.GeoLocation();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Description.Description }
     * 
     */
    public DataCiteMetadataV3 .Description.Description createDataCiteMetadataV3DescriptionDescription() {
        return new DataCiteMetadataV3 .Description.Description();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .RightsList.Right }
     * 
     */
    public DataCiteMetadataV3 .RightsList.Right createDataCiteMetadataV3RightsListRight() {
        return new DataCiteMetadataV3 .RightsList.Right();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .RelatedIdentifiers.RelatedIdentifier }
     * 
     */
    public DataCiteMetadataV3 .RelatedIdentifiers.RelatedIdentifier createDataCiteMetadataV3RelatedIdentifiersRelatedIdentifier() {
        return new DataCiteMetadataV3 .RelatedIdentifiers.RelatedIdentifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .AlternateIdentifiers.AlternateIdentifier }
     * 
     */
    public DataCiteMetadataV3 .AlternateIdentifiers.AlternateIdentifier createDataCiteMetadataV3AlternateIdentifiersAlternateIdentifier() {
        return new DataCiteMetadataV3 .AlternateIdentifiers.AlternateIdentifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Dates.Dates }
     * 
     */
    public DataCiteMetadataV3 .Dates.Dates createDataCiteMetadataV3DatesDates() {
        return new DataCiteMetadataV3 .Dates.Dates();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Contributors.Contributor.NameIdentifier }
     * 
     */
    public DataCiteMetadataV3 .Contributors.Contributor.NameIdentifier createDataCiteMetadataV3ContributorsContributorNameIdentifier() {
        return new DataCiteMetadataV3 .Contributors.Contributor.NameIdentifier();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Subjects.Subject }
     * 
     */
    public DataCiteMetadataV3 .Subjects.Subject createDataCiteMetadataV3SubjectsSubject() {
        return new DataCiteMetadataV3 .Subjects.Subject();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Titles.Titles }
     * 
     */
    public DataCiteMetadataV3 .Titles.Titles createDataCiteMetadataV3TitlesTitles() {
        return new DataCiteMetadataV3 .Titles.Titles();
    }

    /**
     * Create an instance of {@link DataCiteMetadataV3 .Creators.Creator.NameIdentifier }
     * 
     */
    public DataCiteMetadataV3 .Creators.Creator.NameIdentifier createDataCiteMetadataV3CreatorsCreatorNameIdentifier() {
        return new DataCiteMetadataV3 .Creators.Creator.NameIdentifier();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://datacite.org/schema/kernel-3", name = "br", scope = DataCiteMetadataV3 .Description.Description.class)
    public JAXBElement<String> createDataCiteMetadataV3DescriptionDescriptionBr(String value) {
        return new JAXBElement<String>(_DataCiteMetadataV3DescriptionDescriptionBr_QNAME, String.class, DataCiteMetadataV3 .Description.Description.class, value);
    }

}
